### ISSUE TITLE
Criminal Law

### ISSUE THREAD

**Issue by arichiv** [AriChivukula/limbo#70]
# Class 1 (1/7): Chap. 1—Introduction to the Course and to Criminal Law
## A. Nature, Sources and Limits of Criminal Law
- [x] pp. 1-6
# Class 2 (1/8): Chap. 1—continued
## B. Procedural Context: Pre-Trial
- [x] 6-8
## C. Procedural Context: Trial
- [x] 8-9
## D. Proof of Guilt
- [x] 9-12
- [x] 14-19
- [Owens v. State](https://www.quimbee.com/cases/owens-v-state)
# Class 3 (1/9): Chap. 2—Principles of punishment
## A. Theories of Punishment
- [x] 31-35
- [x] 36-42
# Class 4 (1/14): Chap. 2—continued
- [x] Murphy & Hampton, Note 2 49-51
- [x] MPC 1.02(2) 1012-1013
## B. Penal Theories in Action
- [x] [Regina v. Dudley and Stephens](https://www.quimbee.com/cases/regina-v-dudley-and-stephens-14-q-b-d-273-1884), Notes 1, 3 52-54
- [x] Notes 6, 7, 8 63-64
# Class 5 (1/15): Chap. 2—continued
- [x] Weller sentencing exercise, case file Handout # 1
# Class 6 (1/16): Chap. 2—continued
## C. Proportionality
- [x] Kant, Bentham, Constitutional Principles 73-75
- [x] [Coker](https://www.quimbee.com/cases/coker-v-georgia), Notes 3, 4, [Ewing](https://www.quimbee.com/cases/ewing-v-california--2) 76-92
- [x] [Miller v. Alabama](https://www.quimbee.com/cases/miller-v-alabama) Handout # 2
# Class 7 (1/22): Chap. 3—Criminal Statutes
## A. Legality
- [x] CPC 6, 16 (Statutory Supplement)
- [x] [Commonwealth v. Mochan](https://www.quimbee.com/cases/commonwealth-v-mochan) [Keeler v. Superior Court](https://www.quimbee.com/cases/keeler-v-superior-court--2) 93-106
# Class 8 (1/23): Chap. 3—continued
- [x] [Desertrain v. City of Los Angeles](https://www.quimbee.com/cases/desertrain-v-city-of-los-angeles) 111-120
## B. Interpretation
- [x] [Yates v. United States](https://www.quimbee.com/cases/yates-v-united-states) 122-132
# Class 9 (1/25): Chap. 4—Actus Reus
## A. Voluntary Act
- [x] [Martin v. State](https://www.quimbee.com/cases/martin-v-state) 133-136
- [x] MPC 1.13, 2.01 (1017-1019)
- [x] [State v. Utter](https://www.quimbee.com/cases/state-v-utter) 137-142
# Class 10 (1/28): Chap. 4—continued
- [x] [Robinson](https://www.quimbee.com/cases/robinson-v-california), [Powell](https://www.quimbee.com/cases/powell-v-texas), Note 2 728-745
## B. Omissions
- [x] [Beardsley](https://www.quimbee.com/cases/people-v-beardsley), Notes 1, 2, 4 143-149
# Class 11 (1/29): Chap. 4—continued
- [x] [Barber](https://www.quimbee.com/cases/barber-v-superior-court) 149-153
## C. Social Harm
- [x] Introduction, Notes 1, 2 154-156
- [x] [Lawrence v. Texas](https://www.quimbee.com/cases/lawrence-v-texas) Handout # 2
# Class 12 (1/30): The Crime of Possession—Actus Reus, Mens Rea, Policing, and the “War on Crime”
- [x] [United States v. Maldonado](https://www.quimbee.com/cases/united-states-v-maldonado), Dubber Handout # 2
- [x] CPC 466, 12021; CH&W 11350, 11351, 11351.5 Statutory Supplement
# Class 13 (2/4): Chap. 5—Mens Rea
## A. Nature of Mens Rea
- [x] [Cordoba-Hincapie](https://www.quimbee.com/cases/united-states-v-cordoba-hincapie--2), Notes 1, 2 157-158
- [x] CPC 20 Statutory Supplement
- [x] [Cunningham](https://www.quimbee.com/cases/regina-v-cunningham), Note 1 159-161
## B. General Issues
- [x] [Conley](https://www.quimbee.com/cases/people-v-conley), Notes 1-7 161-168
- [x] CPC 240, 241, 242, 243 Statutory Supplement
# Class 14 (2/5): Chap. 5—continued
- [x] MPC approach (Comment & ALI) 169-172
- [x] MPC 1.13, 2.02 1017-1021
- [x] CPC 7 Statutory Supplement
- [x] [Nations](https://www.quimbee.com/cases/state-v-nations), Notes 2, 3, 4 173-177
- [x] [Flores-Figueroa](https://www.quimbee.com/cases/flores-figueroa-v-united-states) 178-184
# Class 15 (2/6): Chap. 5—continued
## C. Strict Liability Offenses
- [x] Note 1, Staples, Notes 1, 2 188-196
- [x] [Garnett](https://www.quimbee.com/cases/garnett-v-state), Notes 2, 3 198-205
- [x] MPC 2.02(3), 2.05 1020, 1022-1023
# Class 16 (2/11): Chap. 5—continued
## D. Mistake and Mens Rea
- [x] [Navarro](https://www.quimbee.com/cases/people-v-navarro), Note 1, 206-208
- [x] MPC 2.04 1022
- [x] [Marrero](https://www.quimbee.com/cases/people-v-marrero), Note 3, Cheek 211-218, 220-226
# Class 17 (2/12): Chap. 6—Causation
## A. Actual Cause
- [x] [Burrage v. United States](https://www.scotusblog.com/case-files/cases/burrage-v-united-states/) Handout #2
## B. Proximate (“Legal”) Cause
- [x] Introduction, [Rideout](https://www.quimbee.com/cases/people-v-rideout), Notes 2, 3, 4, 5, 10 235-243, 245-246
- [x] MPC 2.03 1021
- [x] [Velazquez](https://www.quimbee.com/cases/velazquez-v-state), Note 2 246-249
# Class 18 (2/13): Chap. 7—Homicide
## A. Overview
- [x] Statistics, Origins & Reform; skim Statutes (omit casebook version of California statutes) 253-265
- [x] CPC 187, 188 (both versions), 189 (both versions),
- [x] 189.5, 190.1, 192, 192.5, 193, 194 Statutory Supplement
- [x] MPC 210.0, 210.1, 210.2, 210.3, 210.4, 210.5 1055-1056
## B. Intentional Killings
- [x] [Guthrie](https://www.quimbee.com/cases/state-v-guthrie), Notes 2, 3, 4, 5 273-277
- [x] [Midgett](https://www.quimbee.com/cases/midgett-v-state), Note 1, Forrest, Note 1 277-283
# Class 19 (2/19): Chap. 7—continued
- [x] [Girouard](https://www.quimbee.com/cases/girouard-v-state), Notes 1, 2, 3, 4, 5, 7 285-292
- [x] Dressler article excerpts 292-296
- [x] Introductory Comment 297
- [x] Notes 3, 4 5 300-303
- [x] [Casassa](https://www.quimbee.com/cases/people-v-casassa), Notes 2, 7 303-309, 312
# Class 20 (2/20): Chap. 7—continued
## C. Unintentional Killings: Unjustified Risk-Taking
- [x] Introduction, [Knoller](https://www.quimbee.com/cases/people-v-knoller), Notes 1, 2, 6, 7, 8 316-325
- [x] [Williams](https://www.quimbee.com/cases/state-v-williams), Notes 3, 4, 5, 8, 10 325-330, 332-333
# Class 21 (2/25): Chap. 7—continued
## D. Unintentional Killings: Unlawful Conduct
- [x] Felony-Murder Doctrine, ALI Comment, [Fuller](https://www.quimbee.com/cases/people-v-fuller) 333-336
- [x] Review CPC 188, 189 Statutory Supplement
- [x] Legislative History for SB 1437 (Committee Report) Handout #3
- [x] Overview, [Howard](https://www.quimbee.com/cases/people-v-howard), Notes 1, 2, 4 345-352
# Class 22 (2/26): Chap. 7—continued
- [x] [Smith](https://www.quimbee.com/cases/people-v-smith), Note 1 353-357
- [x] [Sophophone](https://www.quimbee.com/cases/state-v-sophophone) 359-362
- [x] Misdemeanor Manslaughter Rule 363-364
# Class 23 (2/27): Chap. 9—General Defenses to Crimes
## A. Categories of Defenses
- [x] [Robinson](https://www.quimbee.com/cases/robinson-v-california), Dressler 501-507
## B. Burden of Proof
- [x] [Patterson](https://www.quimbee.com/cases/patterson-v-new-york), Notes 1, 2 508-517
## C. Principles of Justification
- [x] Dressler 517-520
# Class 24 (3/4): Chap. 9—continued
- [x] [Peterson](https://www.quimbee.com/cases/united-states-v-peterson--2), Notes 2-9 521-532
- [x] MPC 3.01, 3.02, 3.03, 3.04, 3.07, 3.09 1029-1031, 1035-1037, 1039
- [x] [Goetz](https://www.quimbee.com/cases/people-v-goetz), Notes 1, 3, 4, 6, 7, 8, 10 534-548
# Class 25 (3/5): Chap. 9—continued
- [x] [Wanrow](https://www.quimbee.com/cases/state-v-wanrow), Notes 1, 2, 5-8 548-556
- [x] Battered Women, Norman (both), Notes 2, 3, 6, 12 556-566, 570-572 [A](https://www.quimbee.com/cases/state-v-norman) [B](https://www.quimbee.com/cases/state-v-norman-378-s-e-2d-8-n-c-1989)
# Class 26 (3/6): Chap. 9—continued
- [x] [Boyett](https://www.quimbee.com/cases/state-v-boyett), Notes 1, 2, 3, MPC 3.06 580-585, 1032-1035
- [x] [Nelson](https://www.quimbee.com/cases/nelson-v-state), ALI Comment 586-591
- [x] [Dudley & Stephens](https://www.quimbee.com/cases/regina-v-dudley-and-stephens-14-q-b-d-273-1884) redux, Notes 1-3 601-606
# Class 27 (3/11): Killings by Police
- [x] Supplemental materials Handout #3
# Class 28 (3/12): Chap. 9—continued
## D. Principles of Excuse
- [x] Dressler 610-612
- [x] [Contento-Pachon](https://www.quimbee.com/cases/united-states-v-contento-pachon), Notes 3, 6, 7, 8 613-620
- [x] MPC 2.09 1027
- [x] [Anderson](https://www.quimbee.com/cases/people-v-anderson), Note 2 628-634
- [x] [Veatch](https://www.quimbee.com/cases/united-states-v-veach) 634-637
# Class 29 (3/13): Chap. 9—continued
- [x] Introduction to Insanity, [Freeman](https://www.quimbee.com/cases/united-states-v-freeman), Notes 1-7 642-649
- [x] [Johnson](https://www.quimbee.com/cases/state-v-johnson), ALI Comment, Notes 1-6 649-659
- [x] CPC 21(b), 25(b) Statutory Supplement
- [x] MPC 4.01, 4.03 1040-1041
# Class 30 (3/18): Chap. 9—continued
- [x] [Wilson](https://www.quimbee.com/cases/state-v-wilson), Notes 2, 3 663-673
- [x] Morse 683-685
- [x] CPC 28 Statutory Supplement
- [x] [Clark](https://www.quimbee.com/cases/clark-v-arizona) 689-698
# Class 31 (3/19): Chap. 9—continued
- [x] Review Problem: The case of Mr. Jones Handout # 4
- [x] [Devon T](https://www.quimbee.com/cases/in-re-devon-t) 699-706
- [x] Severe Environmental Deprivation, Delgado 745-747
- [x] Introduction, Cultural Defense in the Criminal Law 748-749, 753-757
# Class 32 (3/20): Chap. 8—Rape
## A. Overview
- [x] Statistics, Notes 1-4, Estrich article excerpts, Notes 1, 2 407-416
- [x] Capers article (Real Rape Too) excerpts Handout # 4
- [x] Proposed MPC Revisions Handout #4
- [x] CPC 261, 261.5, 261.6, 262, 263 Statutory Supplement
## B. Forcible Rape
- [x] [Rusk I](https://www.quimbee.com/cases/state-v-rusk), [Rusk II](https://www.quimbee.com/cases/rusk-v-state), Note 4 (Brown) 440-449
# Class 33 (4/1): Chap. 8—continued
- [x] M.T.S., Notes 1, 3, 4, 9 464-474, 476-477
- [x] [Lopez](https://www.quimbee.com/cases/united-states-v-lopez--2), Note 1 477-482
## C. [E. in the casebook] Statutory Rape
- [x] [Garnett](https://www.quimbee.com/cases/garnett-v-state) 198-204
- [x] Note 3 497
# Class 34 (4/2): Chap. 10—Inchoate Offenses
## A. Overview
- [x] ALI Comment, Notes 1, 2 761-764
## B. Attempt
- [x] Robbins, Note 1, Ashworth 764-767
- [x] MPC 5.01, 5.05 1046-1048, 1050-1051
- [x] ALI Comment 769-770
- [x] CPC 21a, 664 Statutory supplement
- [x] [Gentry](https://www.quimbee.com/cases/people-v-gentry), Notes 1, 3, 4, Bruce, Notes 1, 2 771-774, 775-778
# Class 35 (4/3): Chap. 10—continued
- [x] [Mandujano](https://www.quimbee.com/cases/united-states-v-mandujano), Note 1 (A-E) 779-782
- [x] [Rizzo](https://www.quimbee.com/cases/people-v-rizzo), [Miller](https://www.quimbee.com/cases/people-v-miller), Note 1 787-791
- [x] [Reeves](https://www.quimbee.com/cases/state-v-reeves), Notes 2, 3 792-798
# Class 36 (4/8): Chap. 10—continued
- [x] [Thousand](https://www.quimbee.com/cases/people-v-thousand), Notes 2, 3 800-809
- [x] [McCloskey](https://www.quimbee.com/cases/commonwealth-v-mccloskey), Notes 1, 2 816-819
- [x] ALI Commentary, Note 3 820-823
## C. Solicitation
- [x] [Mann](https://www.quimbee.com/cases/state-v-mann), Notes 1, 2 830-831
- [x] MPC 5.02 1048
## D. Conspiracy
- [x] [Carter](https://www.quimbee.com/cases/people-v-carter) 836
# Class 37 (4/9): Chap. 10—continued
- [x] [Pinkerton](https://www.quimbee.com/cases/pinkerton-v-united-states), Notes 1, 4 840-844
- [x] [Swain](https://www.quimbee.com/cases/people-v-swain) 844-847
- [x] [Azim](https://www.quimbee.com/cases/commonwealth-v-azim) 857-858
- [x] ALI Comment, Kilgore, Notes 1, 2, 3, 4 870-876
- [x] 18 U.S.C. sec. 371 Statutory supplement
# Class 38 (4/10): Chap. 11—Liability for the Conduct of Another
## A. Accomplice Liability
- [x] [Ward](https://www.quimbee.com/cases/state-v-ward), Note 1, Theoretical Foundation 891-894
- [x] [Hoselton](https://www.quimbee.com/cases/state-v-hoselton), Notes 1, 2 895-898
- [x] MPC 2.06 1023-1024
- [x] Rosemond v. United States Handout # 4
- [x] Notes 1, 2 (omit Lauria) 899-901
# Class 39 (4/15): Chap. 11—continued
- [x] [Riley](https://www.quimbee.com/cases/riley-v-state), Note 1 901-906
- [x] Review Legislative History for SB 1437 (Committee Rep.) Handout #3
- [x] [Linscott](https://www.quimbee.com/cases/state-v-linscott), Notes 1, 2 909-913
- [x] [V.T.](https://www.quimbee.com/cases/state-v-v-t), Notes 1, 2, 3 913-915
# Class 40 (4/16): Chap. 11—continued
- [x] [Wilcox](https://www.quimbee.com/cases/wilcox-v-jeffery) 915-917
- [x] Note 4, Genoa 922-924
- [x] [Bailey](https://www.quimbee.com/cases/bailey-v-commonwealth), [Lopez](https://www.quimbee.com/cases/united-states-v-lopez--2), [McCoy](https://www.quimbee.com/cases/people-v-mccoy) 925-934
- [x] Megan R., [Formella](https://www.quimbee.com/cases/state-v-formella) 935-940
- Optional on-line Quiz #5.
# Class 41 (4/17): Chap. 11—continued
## B. (D in book) Corporate Liability
- [x] [Christy Pontiac-GMC](https://www.quimbee.com/cases/state-v-christy-pontiac-gmc-inc) 946-950
- [x] MPC 2.07 1024-1026
- [x] Bucy excerpt, Note 1 950-953
- [x] Article excerpt; US Atty Manual Handout # 4
# Class 42 (4/22): Chap. 11—continued
- [x] Hypo—Corporate Criminal Liability Exercise Handout # 4
- [x] Review Problem Handout # 4
